server:
  port: 8080
  servlet:
    context-path: /
 
spring:
  servlet:
    multipart:
      max-request-size: 3000MB
      max-file-size: 3000MB
      
  thymeleaf:
    prefix: classpath:templates/ 
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false
    order: 0
  
  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:mariadb://mariadb:3306/kreblog?useTimezone=true&serverTimezone=Asia/Seoul&useSSL=false
    username: kre
    password: kre1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    